
spring:
  application:
    name: funeralsvc

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  datasource:
    url: ENC(w92N2YheEDgCtNhXgvbiGEg98Yzky6U9C5JwdnP0I05hTqEbfbDRuQDXnsXG2F6E/zFR6xswJuMd61gyVLB9VC3DFUk55Um7toXVpzkvAIjta4+PiOsXkAHFuWTmv9Gy)
#    url: ENC(3ZmhV6Lp//NGOjMS2YD128xwtF5f3ul2DGzzwtBTyfQFGwXwEg2LY4w8ReI2EvLGEnV9clXq4hlkaEkUNPU2QrZhyy9TbT9LvlPPe0kTJ7Y=)
    username: ENC(7uZDhUQl6j6udzv0AvWv6u+HeisKEiF4purzMBnLIT3NVzmQgFDY1BsGyhGnFu5b)
    password: ENC(CmFEJ4gGLtgtc79GlXMWoBybsm9Hx8WviOiN/Wl1EZQojqzBvkCgPDfyF4GIsTDE)
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
#      ddl-auto: create
      ddl-auto: update
      database: postgresql
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect


##############
server:
  port: 9022
########################################
## RabbitMq AMQP
########################################
rabbitmq_amqp:
  url: ENC(XyopeRRqJLqk2drgTwI/M5q5O8Zviaa8Ie5jng7ly7rbDi0uSZmjAz4z50fOzXwLgfoH+rnEgOY3mVBoArcDeQ==)
  username: ENC(F0ZnciLS6gbua2E2l4/iTfoaEudXJ5XeWDcshH7FyO3f7m05ef+WtgRUHQG6ZlTS)
  password: ENC(tyX1HdGAFEQAiG1jcNheUcyeMq5OikMlXWl5I71VZ9L92ddGcCS/TRLEbDEYT9qXa+C8DcqNe9UuErPaoPoRWA==)


funeral:
  agent:
    url: ENC(4khkUHE4O3O6KANMmVGya8rV5/lbvwoqSPMT/UidfMypYkoSyH74UIBlLiSzQY/8OfmguhTOcAmcSr2+Ms4JmA==)
    reservation-path: /api/kt/petcare/care
    username : ENC(FOU52rX3xHsvPvZtiPSufF9NR6mGNs4Gh7T9u5ooJdcRnrrFSjdrmclmijgYr8GL)
    password : ENC(+2gb1OYtrXZDyDFFgwz9jyMl4GVTN21HlJaSi4VI9wQze2CEUp+y0/aAqoAywehy)

user-service:
  url: ENC(yPH30kuBGCwzOzCS9e/jr9OJqsQns91Aw7kKj6Ct+57nj69uR7/Eoaxg9nJhPMMWq/fsQWT+iotwXQwLuadfwQ==)
  userinfo-path: /pcp/user/v1/internal/userinfo

##############
## LOGGING
##############
logging:
#  level:
#    org.hibernate.SQL: DEBUG
#    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
#    org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration: DEBUG
#    com.zaxxer.hikari: DEBUG

  config: file:/home/petcare/svc/FUNERAL/config/logback-spring.xml
  file:
    path: /home/petcare/log/FUNERAL
